### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/EVTXtract#10]
```
Traceback (most recent call last):
  File "evtxtract/main.py", line 83, in <module>
  File "evtxtract/main.py", line 58, in main
  File "evtxtract/__init__.py", line 98, in extract
  File "evtxtract/templates.py", line 146, in insert_substitutions
  File "/home/user/env/lib/python2.7/re.py", line 155, in sub
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 1: ordinal not in range(128)
```

**Comment by williballenthin** [comment]
binary type nodes were not being encoded. fixed in 88d4dc95e896d97e9f80133ce7b102c9bd74eb03, with these nodes being hex-encoded.
