### ISSUE TITLE
XMLSyntaxError: EntityRef: 

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/EVTXtract#11]
tag005-disk1 offset 0xB64B7E4A8

```
Traceback (most recent call last):
  File "evtxtract/carvers.py", line 213, in extract_chunk_templates
  File "evtxtract/templates.py", line 229, in get_template
  File "evtxtract/utils.py", line 48, in get_eid
  File "evtxtract/utils.py", line 18, in to_lxml
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79003)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118334)
  File "src/lxml/parser.pxi", line 1729, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:116892)
  File "src/lxml/parser.pxi", line 1063, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:110879)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
XMLSyntaxError: EntityRef: expecting ';', line 15, column 117 (line 15)
```

**Comment by williballenthin** [comment]
same as #12. fixed upstream
