### ISSUE TITLE
XMLSyntaxError: xmlParseEntityRef:

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/EVTXtract#12]
tag005-disk1  offset 0x4E84EB798

```
Traceback (most recent call last):
  File "evtxtract/carvers.py", line 213, in extract_chunk_templates
  File "evtxtract/templates.py", line 229, in get_template
  File "evtxtract/utils.py", line 48, in get_eid
  File "evtxtract/utils.py", line 18, in to_lxml
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79003)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118334)
  File "src/lxml/parser.pxi", line 1729, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:116892)
  File "src/lxml/parser.pxi", line 1063, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:110879)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
XMLSyntaxError: xmlParseEntityRef: no name, line 12, column 73 (line 12)
```

**Comment by williballenthin** [comment]
this is due to embedded ampersands (`&`) like the following element:

    <string>DeviceIoControl(\\?\fdc#generic_floppy_drive#6&2bc13940&0&0#{53f5630d-b6bf-11d0-94f2-00a0c91efb8b} - 000000000000041C,0x00560000,0000000000000000,0,0000000000484930,4096,[0])</string>

seems like the fix is to replace ampersands with `&amp;`?

**Comment by williballenthin** [comment]
fixed upstream in python-evtx
