### ISSUE TITLE
OverrunBufferException

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/EVTXtract#14]
```
Traceback (most recent call last):  
File "evtxtract/carvers.py", line 174, in extract_chunk_records  
File "Evtx/Views.py", line 186, in evtx_record_xml_view  
File "Evtx/Views.py", line 169, in _build_record_xml  
File "Evtx/Views.py", line 160, in rec  
File "Evtx/Views.py", line 156, in rec  
File "Evtx/BinaryParser.py", line 64, in call  
File "Evtx/Nodes.py", line 1002, in fast_substitutions  
File "Evtx/BinaryParser.py", line 534, in unpack_systemtimeOverrunBufferException: Tried to parse beyond the end of the file (read: 0x5a26a7b50, buffer length: 0x1900000000)
Killed
```

**Comment by williballenthin** [comment]
this exception should be correctly handled by the catched `except Exception` statement on line 190.
i think the `Killed` notice is unrelated, possibly from the OOM killer on the system.
