### ISSUE TITLE
TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by JumpingJacks800** [williballenthin/EVTXtract#9]
Good day I have been trying to get the program to parse through an .001, DD, .bin file and each and every time I tried I received the following error

```
C:\Python34\EVTXtract-master>python find_evtx_chunks.py "G:\Unallocated Clusters
.bin" Test1 Test1 --progress
Traceback (most recent call last):
  File "find_evtx_chunks.py", line 91, in main
    num_chunks_found = find_evtx_chunks(state, buf, progress_class=args.progress
_class)
  File "find_evtx_chunks.py", line 67, in find_evtx_chunks
    index = buf.find(EVTX_HEADER_MAGIC)
TypeError: 'str' does not support the buffer interface

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "find_evtx_chunks.py", line 96, in <module>
    main()
  File "find_evtx_chunks.py", line 91, in main
    num_chunks_found = find_evtx_chunks(state, buf, progress_class=args.progress
_class)
  File "C:\Python34\EVTXtract-master\State.py", line 84, in __exit__
    indent=4, separators=(',', ': ')))
TypeError: 'str' does not support the buffer interface
```

```
C:\Python34\EVTXtract-master>python find_evtx_chunks.py --vverbose "G:\Unallocat
ed Clusters.bin" Test1 Test1 --progress
2016-03-01 11:51:13,040 DEBUG state Using existing state file: Test1.json
Traceback (most recent call last):
  File "find_evtx_chunks.py", line 91, in main
    num_chunks_found = find_evtx_chunks(state, buf, progress_class=args.progress
_class)
  File "find_evtx_chunks.py", line 67, in find_evtx_chunks
    index = buf.find(EVTX_HEADER_MAGIC)
TypeError: 'str' does not support the buffer interface

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "find_evtx_chunks.py", line 96, in <module>
    main()
  File "find_evtx_chunks.py", line 91, in main
    num_chunks_found = find_evtx_chunks(state, buf, progress_class=args.progress
_class)
  File "C:\Python34\EVTXtract-master\State.py", line 84, in __exit__
    indent=4, separators=(',', ': ')))
TypeError: 'str' does not support the buffer interface
```

Could someone please help me understand the problem please?

**Comment by williballenthin** [comment]
EVTXtract is a script that currently depends on Python2.7, and will not work with Python3 yet. Would you try again using a python2.7 interpreter?
